version: "3.8"

services:
  frontend:
    container_name: tele-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
